import React from 'react';

export default function MissionLog({ currentLevel }) {
  // IDs now start at 0 to match Solidity totalQuests
    const missions = [
        { id: 0, title: "The Unity Fountain Start", reward: "0.01 ETH" },
            { id: 1, title: "The Secret Gate of Wuse", reward: "0.02 ETH" },
                { id: 2, title: "The Golden Summit (Maitama)", reward: "0.05 ETH" }
                  ];

                    return (
                        <section className="mt-8">
                              <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-4">
                                      Mission Log
                                            </h3>
                                                  <div className="space-y-3">
                                                          {missions.map((m) => {
                                                                    const isCompleted = m.id < currentLevel;
                                                                              const isActive = m.id === currentLevel;
                                                                                        const isLocked = m.id > currentLevel;

                                                                                                  return (
                                                                                                              <div 
                                                                                                                            key={m.id}
                                                                                                                                          className={`p-4 rounded-xl border transition-all ${
                                                                                                                                                          isCompleted 
                                                                                                                                                                            ? "bg-green-900/20 border-green-500/50 opacity-70" 
                                                                                                                                                                                              : isActive 
                                                                                                                                                                                                                ? "bg-blue-900/20 border-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.3)]"
                                                                                                                                                                                                                                  : "bg-slate-800/50 border-slate-700 grayscale"
                                                                                                                                                                                                                                                }`}
                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                          <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                            <span className={`text-xs font-bold ${isActive ? "text-blue-400" : "text-slate-500"}`}>
                                                                                                                                                                                                                                                                                                                                LEVEL {m.id}
                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                    <span className={`${isCompleted ? "line-through text-slate-500" : "text-slate-200"}`}>
                                                                                                                                                                                                                                                                                                                                                                                        {m.title}
                                                                                                                                                                                                                                                                                                                                                                                                          </span>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-xs font-mono text-blue-400 bg-blue-900/30 px-2 py-1 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {m.reward}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {isActive && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-2 text-[10px] text-blue-300 animate-pulse">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ● Active Mission: Find the secret to unlock reward
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }