// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/metatx/ERC2771Context.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract BigViewMission is ERC2771Context, Ownable, ReentrancyGuard {
    
        struct Quest {
                bytes32 secretHash; 
                        uint256 reward;     
                                bool isClaimed;      
                                        uint256 totalPricePool;
                                                string name;
                                                        uint256 entryFee;
                                                                bool isActive;
                                                                        uint256 deadline;    
                                                                            }

                                                                                mapping(uint256 => Quest) public quests;
                                                                                    mapping(address => uint256) public playerLevel;
                                                                                        mapping(address => mapping(uint256 => bool)) public hasCompletedQuest;
                                                                                            mapping(uint256 => mapping(address => bool)) public hasJoined;
                                                                                                mapping(address => bytes32) public submissionCommitments;

                                                                                                    uint256 public totalQuests;

                                                                                                        event QuestJoined(uint256 indexed _questId, address indexed player);
                                                                                                            event QuestSolved(address indexed player, uint256 questId, uint256 reward);

                                                                                                                // Using the official EntryPoint for True AA (Base Sepolia)
                                                                                                                    constructor() ERC2771Context(0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789) Ownable(msg.sender) {}

                                                                                                                        function launchNewQuest(string memory _name, uint256 _reward, uint256 _fee, bytes32 _secretHash, uint256 _durationMinutes) public onlyOwner {
                                                                                                                                quests[totalQuests] = Quest({
                                                                                                                                            secretHash: _secretHash,
                                                                                                                                                        reward: _reward,
                                                                                                                                                                    isClaimed: false,
                                                                                                                                                                                totalPricePool: 0,
                                                                                                                                                                                            name: _name,
                                                                                                                                                                                                        entryFee: _fee,
                                                                                                                                                                                                                    isActive: true,
                                                                                                                                                                                                                                deadline: block.timestamp + (_durationMinutes * 1 minutes)
                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                totalQuests++;
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        function joinQuest(uint256 _questId) public payable {
                                                                                                                                                                                                                                                                address player = _msgSender(); 
                                                                                                                                                                                                                                                                        Quest storage quest = quests[_questId];
                                                                                                                                                                                                                                                                                require(quest.isActive, "Mission Not active");
                                                                                                                                                                                                                                                                                        require(playerLevel[player] == _questId, "Complete previous levels first!");
                                                                                                                                                                                                                                                                                                require(msg.value >= quest.entryFee, "Insufficient fee");
                                                                                                                                                                                                                                                                                                        hasJoined[_questId][player] = true;
                                                                                                                                                                                                                                                                                                                quest.totalPricePool += quest.entryFee;
                                                                                                                                                                                                                                                                                                                        emit QuestJoined(_questId, player);
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                function claimTreasure(uint256 _questId, string memory _secretKey) public nonReentrant {
                                                                                                                                                                                                                                                                                                                                        address player = _msgSender(); 
                                                                                                                                                                                                                                                                                                                                                Quest storage quest = quests[_questId];
                                                                                                                                                                                                                                                                                                                                                        require(keccak256(abi.encodePacked(_secretKey)) == quest.secretHash, "Wrong key");
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                        uint256 totalAvailable = quest.reward + quest.totalPricePool;
                                                                                                                                                                                                                                                                                                                                                                                quest.isClaimed = true;
                                                                                                                                                                                                                                                                                                                                                                                        playerLevel[player]++;
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                        (bool success, ) = payable(player).call{value: totalAvailable}("");
                                                                                                                                                                                                                                                                                                                                                                                                                require(success, "Transfer failed");
                                                                                                                                                                                                                                                                                                                                                                                                                        emit QuestSolved(player, _questId, totalAvailable);
                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                // --- THE TIE-BREAKERS (REQUIRED TO FIX YOUR ERROR) ---

                                                                                                                                                                                                                                                                                                                                                                                                                                    function _msgSender() internal view override(Context, ERC2771Context) returns (address) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            return ERC2771Context._msgSender();
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    function _msgData() internal view override(Context, ERC2771Context) returns (bytes calldata) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ERC2771Context._msgData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function _contextSuffixLength() internal view override(Context, ERC2771Context) returns (uint256) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return ERC2771Context._contextSuffixLength();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    receive() external payable {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }